version: "3.5"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_zecontinha
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./postgres.env
    #environment:
    #  - POSTGRES_DB
    #  - POSTGRES_USER
    #  - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    networks:
      - zecontinha_network
  app:
    build: .
    container_name: zecontinha
    volumes:
      - .:/src/
      - /var/logs/zecontinha:/srv/logs
    ports:
      - "8000:8000"
    env_file:
      - ./zecontinha.env
    #environment:
    #  - DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    #  - SECRET_KEY
    #  - DATABASE_URL
    #  - BINANCE_APIKEY
    #  - BINANCE_SECRETKEY
    #  - TELEGRAM_API_KEY
    #  - ENV
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - zecontinha_network
networks:
  zecontinha_network:
    name: zecontinha_network
