version: "3.5"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_zecontinha
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vozdocu
      - POSTGRES_USER=vozdocu
      - POSTGRES_PASSWORD=vozdocu
    ports:
      - 5432:5432
  app:
    build: .
    container_name: app_zecontinha
    volumes: 
      - .:/src/
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
      - postgres
    depends_on:
      - postgres
    