[tool.poetry]
name = "zecontinha"
version = "0.1.0"
description = "zecontinha dependencies"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
scipy = "1.6.0"
yfinance = "^0.2.12"
dj-database-url = "^1.2.0"
gunicorn = "^20.1.0"
python-telegram-bot = "12.7"
python-binance = "0.7.5"
matplotlib = "3.5.0"
psycopg2 = "^2.9.5"
ipython = "7.6.1"
ipython-genutils = "0.2.0"
psycopg-binary = "^3.1.8"
statsmodels = "0.11.1"
whitenoise = "4.1.3"
python-decouple = "3.3"
django = "3.2.18"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
